version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roster-backend
    ports:
      - "8089:8089"
    environment:
      - PORT=8089
      - JWT_SECRET=supersecret
    working_dir: /app
    command: ["/app/main"]
