version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roster-backend
    ports:
      - "8089:8089"
    environment:
      - JWT_SECRET=SECRET
    volumes:
      - .:/app                 
